project:
<<<<<<< HEAD
  type: website
=======
  type: book
>>>>>>> 946b5fb0f27eca67d94b53276b2925a05848ea49
  output-dir: docs

book: 
  title: "Introduction to Statistics"
  subtitle: "University of Florida"
  author: "Anthony Raborn"
  date: last-modified
  chapters:
    - index.qmd
    - part: "Lecture Notes - Simple Linear Regression"
      chapters:
        - 01-simple-linear-regression.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

